# 菜单配置（若不需要某项可直接删除）
menu:
  # 首页
  - id: home
    link: /
    icon: home
    class: menu-home
  # 归档
  - id: archives
    link: /archives
    icon: archive
    class: menu-archive
  # 目录
  - id: category
    link: javascript:;
    category: true
    icon: bookmark
    class: menu-category
  # 读书
  - id: reading
    link: /reading
    icon: book
    class: menu-reading
  # 关于我
  - id: about
    link: /about
    icon: user
    class: menu-about
  # 搜索
  - id: search
    link: "#search"
    icon: search
    class: menu-search modal-trigger

# 颜色配置
color:
    header: green
    footer: green
    page_nav: green
    side_nav: green darken-1
    tag: red lighten-1
    article_title_link: green
    link: red
    pagination: red
    tab: red
    archive_item: grey
    fab: red
    fab_2: cyan
    fab_3: light-green
    new: red
    about_header: green
    about_title: green

archive_yearly: true
footer:
  # Specify the date when the site was setup.
  # If not defined, current year will be used.
  since: 2015
  # 版权信息
  copyright:  datablog.top, All rights reserved. 渝ICP备18014633号-1

# Disqus评论shortname，若为空则不启用
disqus_shortname:
# 多说shortname，若为空则不启用
duoshuo_shortname:
# 网易云跟帖productKey，从通用代码中获取，若为空则不启用
yungentie_product_key:
# Valine是一款基于Leancloud的快速、简洁且高效的无后端评论系统。其appid和appkey的获取详见官网：https://valine.js.org/
valine_appid: E1muodnIpfcKK62HaXJuTvAz-gzGzoHsz
valine_appkey: k6L9pbRhpIONaIzaqch9RgtX

# Google分析track id，若为空则不启用
google_analytics:
# 腾讯分析sId，若为空则不启用
tencent_analytics:
#百度分析
baidu_analytics: 014b1209747c209a08544931e71b394c
# 高亮的主题，若为空则使用默认主题
google_code_prettify: tranquil-heart

# 是否启用MathJax数学公式渲染。如果你确认整个站点的博文都不会用到Latex数学公式，可以将其该项设为false提高页面加载速度
mathjax: true

# 是否启用网页计数器（使用不蒜子插件）
page_stat: true
#微信公众号
wechat_subscriber:
  enabled: true
  qcode: /images/mmexport1526034702307.png
  description: 欢迎您扫一扫上面的微信公众号，订阅我的博客！
#声明
statement:
  enabled: true
  description: 声明：本文仅限用于学术交流，引用或转载本文时请注明出处！